### ISSUE TITLE
Display predicted result with a good UI

### ISSUE THREAD

**Issue by thegauravgiri** [NiShApOkHaReL/BangaloreHousePricePrediction#2]
First of all, great job on creating an end to end project. But I saw that the predicted output is not displayed properly. I would like to contribute to this project by working on displaying the predicted output in better way.

**Comment by NiShApOkHaReL** [comment]
Thank you for your concern to this repo, and for the contribution you can fork the repo, make the changes and send the pr request so that you can contribute to it!
